name: "SkyWars"
main: cz.SkyWars.SkyWars
version: "1.0 alpha"
api: ["1.0.0"]
author: "Ragnok123"
load: POSTWORLD
commands:
 sw:
  description: "sw command"
  permission: skywars.command
  default: "op"
  aliases: ["skywars"]
permissions:
 skywars.command:
  description: "Allows player to use /sw command"
  default: op
